### ISSUE TITLE
SIGSEGV creating a new cluster

### ISSUE THREAD

**Issue by MichaelSp** [sapcc/kubernikus#377]
I just tried to create this cluster:
```json
{
  "name": "cc-dev",
  "spec": {
    "nodePools": [
      {
        "flavor": "m2.2xlarge",
        "image": "coreos-stable-amd64",
        "name": "dev",
        "size": 10
      }
    ]
  }
}
```
using this command line

`> kubernikusctl create cluster --file /var/folders/qm/zm6n1z556zs6996kny3r492m0000gn/T/cluster_definition20190212-3588-157oqsw --auth-url ** --url ** --project-id ** --username d0** --user-domain-name monsoon3 --password=****`

Here is what happened:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x171a4ef]

goroutine 1 [running]:
github.com/sapcc/kubernikus/pkg/api/client.(*TransportConfig).WithBasePath(...)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/common/kubernikus.go:22
github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/common.NewKubernikusClient(0x0, 0xc4204d0200, 0xf7, 0xc4200e9cb0)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/common/kubernikus.go:24 +0xaf
github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create.(*CreateOptions).SetupKubernikusClient(0xc420071400, 0x0, 0xd)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create/common.go:46 +0xe1
github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create.(*CreateOptions).clusterPreRun(0xc420071400, 0xc42025a6c0, 0xc420273ad0, 0x0, 0xd)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create/cluster.go:30 +0x65
github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create.(*CreateOptions).(github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create.clusterPreRun)-fm(0xc42025a6c0, 0xc420273ad0, 0x0, 0xd)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/pkg/cmd/kubernikusctl/create/cluster.go:21 +0x52
github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra.(*Command).execute(0xc42025a6c0, 0xc420273860, 0xd, 0xd, 0xc42025a6c0, 0xc420273860)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra/command.go:595 +0x44b
github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42050db00, 0xc420261200, 0xc42025a000, 0xc42025a900)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42050db00, 0xd, 0xc42050db00)
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/Users/d062284/ci.global.cloud.sap/workdir/volumes/live/982b39bb-d46e-4f29-716c-294c53e2a155/volume/gopath/src/github.com/sapcc/kubernikus/cmd/kubernikusctl/main.go:19 
+0xb5
```

**Comment by MichaelSp** [comment]
looks like it's not possible to give the arguments via CLI. They are only read from environment vars
